name: Weekly Sales Report

on:
  # Run on schedule (2 AM UTC every Monday)
  schedule:
    - cron: '0 2 * * 1'
  
  # Allow manual triggering via GitHub UI
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Run in test mode'
        required: false
        default: 'true'
        type: boolean

jobs:
  generate-sales-report:
    runs-on: ubuntu-latest
    env:
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
      AE_EMAILS_CHARMAINE: ${{ secrets.AE_EMAILS_CHARMAINE }}
      AE_EMAILS_WORLDLINK: ${{ secrets.AE_EMAILS_WORLDLINK }}
      AE_EMAILS_HOUSE: ${{ secrets.AE_EMAILS_HOUSE }}
      AE_EMAILS_NATIONAL: ${{ secrets.AE_EMAILS_NATIONAL }}
      DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
      DROPBOX_TEAM_MEMBER_ID: ${{ secrets.DROPBOX_TEAM_MEMBER_ID }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Download files from Dropbox
        run: python scripts/team_dropbox_download.py
      
      - name: Run sales report generator
        run: |
          if ${{ github.event_name == 'workflow_dispatch' && inputs.test_mode }}; then
            python main.py --test
          elif ${{ github.event_name == 'schedule' }}; then
            python main.py
          else
            python main.py
          fi
      
      - name: Upload reports to Dropbox
        run: python scripts/team_dropbox_upload.py
      
      - name: Upload logs and reports as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sales-reports-${{ github.run_id }}
          path: |
            data/reports/**/*.xlsx
            data/reports/logs/*.log
          retention-days: 14
